# Generated by Django 3.2.3 on 2021-06-14 23:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_candidat_copie_correcteur_epreuve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='copie',
            name='idcorrecteur',
        ),
        migrations.RemoveField(
            model_name='correcteur',
            name='specialité',
        ),
        migrations.AddField(
            model_name='candidat',
            name='NumeroTable',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidat',
            name='dateNaiss',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidat',
            name='exclu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidat',
            name='salle',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidat',
            name='specialite',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='copie',
            name='idcorrecteur1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.correcteur'),
        ),
        migrations.AddField(
            model_name='copie',
            name='idcorrecteur2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.correcteur'),
        ),
        migrations.AddField(
            model_name='copie',
            name='idcorrecteur3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.correcteur'),
        ),
        migrations.AddField(
            model_name='copie',
            name='subi3eme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='correcteur',
            name='idepreuve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.epreuve'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='epreuve',
            name='coeff',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ListCandidats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFichier', models.CharField(max_length=100)),
                ('idSpecialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.specialite')),
            ],
        ),
        migrations.CreateModel(
            name='CorrigesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFichier', models.CharField(max_length=100)),
                ('idEpreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.epreuve')),
            ],
        ),
    ]
