# Generated by Django 3.2.3 on 2021-06-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_candidat_specialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='NumeroTable',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='exclu',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='salle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
