# Generated by Django 3.2.3 on 2021-06-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_corrigestype_idepreuve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corrigestype',
            old_name='idEpreuve',
            new_name='Epreuve',
        ),
    ]
