# Generated by Django 3.2.3 on 2021-06-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_idepreuve_corrigestype_epreuve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correcteur',
            name='idepreuve',
        ),
        migrations.AddField(
            model_name='correcteur',
            name='epreuve',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
