# Generated by Django 3.2.3 on 2021-06-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_fichiers'),
        ('app', '0015_alter_copie_subi3eme'),
    ]

    operations = [
    ]
