<<<<<<< HEAD
# Generated by Django 3.2.3 on 2021-06-18 20:44
=======
# Generated by Django 3.2.3 on 2021-06-18 14:23
>>>>>>> e7605174c860c89de55cf437de9c86aeafff760a

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_fichiers'),
        ('app', '0015_alter_copie_subi3eme'),
    ]

    operations = [
    ]
