# Generated by Django 3.2.3 on 2021-06-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_resultat_resultat_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultat_module',
            name='moy_note',
            field=models.FloatField(),
        ),
    ]
