# Generated by Django 3.2.3 on 2021-06-30 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_resultat_module_moy_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlaureat',
            name='user',
        ),
        migrations.DeleteModel(
            name='Affect',
        ),
        migrations.DeleteModel(
            name='UserLaureat',
        ),
    ]
